import { IndicatorHelp } from "./IndicatorHelp"
import type { RadarData } from "../../types/radar"
import { SectionTitle } from "./SectionTitle"

function getClassificationStyle(classification?: string) {
  switch (classification) {
    case "FEATURE_ACTIVATION_CANDIDATE": return { badge: "border-red-500/30 bg-red-500/10 text-red-300", text: "text-red-300", dot: "bg-red-400" }
    case "FEATURE_ACTIVATION_CONVERGENCE": return { badge: "border-amber-500/30 bg-amber-500/10 text-amber-300", text: "text-amber-300", dot: "bg-amber-400" }
    case "FEATURE_SURFACE_TRANSITION":
    case "BUNDLE_SURFACE_DRIFT": return { badge: "border-cyan-500/30 bg-cyan-500/10 text-cyan-300", text: "text-cyan-300", dot: "bg-cyan-400" }
    case "DORMANT_FEATURE_SURFACE": return { badge: "border-slate-500/30 bg-slate-500/10 text-slate-300", text: "text-slate-300", dot: "bg-slate-400" }
    default: return { badge: "border-emerald-500/30 bg-emerald-500/10 text-emerald-300", text: "text-emerald-300", dot: "bg-emerald-400" }
  }
}
function semanticTone(level?: string) {
  switch (level) { case "CRITICAL": return "text-red-300 border-red-500/30 bg-red-500/10"; case "HIGH": return "text-orange-300 border-orange-500/30 bg-orange-500/10"; case "MEDIUM": return "text-yellow-300 border-yellow-500/30 bg-yellow-500/10"; case "LOW": return "text-cyan-300 border-cyan-500/30 bg-cyan-500/10"; default: return "text-slate-300 border-white/10 bg-white/5" }
}
function timelineTone(classification?: string) {
  switch (classification) { case "COORDINATED_ACTIVATION_CANDIDATE": return "border-red-500/30 bg-red-500/10 text-red-300"; case "ACTIVATION_SEQUENCE": return "border-orange-500/30 bg-orange-500/10 text-orange-300"; case "SURFACE_TRANSITION": return "border-amber-500/30 bg-amber-500/10 text-amber-300"; case "MULTI_DOMAIN_ACTIVITY": return "border-cyan-500/30 bg-cyan-500/10 text-cyan-300"; default: return "border-emerald-500/30 bg-emerald-500/10 text-emerald-300" }
}
function confidenceTone(level?: string) {
  switch (level) { case "VERY_HIGH": return "text-emerald-300"; case "HIGH": return "text-cyan-300"; case "MEDIUM": return "text-yellow-300"; case "LOW": return "text-orange-300"; case "VERY_LOW": return "text-red-300"; default: return "text-slate-400" }
}
function decisionTone(state?: string) {
  switch (state) {
    case "CRITICAL_ACTIVATION_CANDIDATE": return "border-red-500/30 bg-red-500/10 text-red-300"
    case "HIGH_CONFIDENCE_CONVERGENCE": return "border-orange-500/30 bg-orange-500/10 text-orange-300"
    case "RUNTIME_ACTIVATION": return "border-amber-500/30 bg-amber-500/10 text-amber-300"
    case "STRUCTURAL_CHANGE": return "border-fuchsia-500/30 bg-fuchsia-500/10 text-fuchsia-300"
    case "WATCH": return "border-cyan-500/30 bg-cyan-500/10 text-cyan-300"
    default: return "border-emerald-500/30 bg-emerald-500/10 text-emerald-300"
  }
}
function shortHash(value?: string | null) { if (!value) return "—"; return value.length > 16 ? `${value.slice(0, 8)}…${value.slice(-8)}` : value }
function shortEventType(value?: string) { return String(value || "UNKNOWN").replaceAll("_", " ") }

export function FeatureActivationPanel({ data }: { data?: RadarData | null }) {
  const evidence = data?.featureActivationEvidence
  const intelligence = evidence as any
  const bundleDiff = intelligence?.bundleDiff || null
  const semanticChange = intelligence?.semanticChange || null
  const routeApi = (data as any)?.routeApiIntelligence || null
  const activationTimeline = (data as any)?.activationTimeline || null
  const activationDecision = (data as any)?.activationDecision || null
  const evidenceConfidence = activationTimeline?.evidenceConfidence || null
  const strongestEvidence = Array.isArray(evidenceConfidence?.strongestEvidence) ? evidenceConfidence.strongestEvidence : []
  const decisionReasons = Array.isArray(activationDecision?.reasons) ? activationDecision.reasons : []
  const classification = evidence?.classification || "UNKNOWN"
  const style = getClassificationStyle(classification)
  const dormantRoutes = evidence?.observedDormantRoutes || []
  const activatedRoutes = evidence?.activatedRoutes || []
  const unlockedFlags = evidence?.unlockedFlags || []
  const addedBundles = Array.isArray(bundleDiff?.addedBundles) ? bundleDiff.addedBundles : []
  const removedBundles = Array.isArray(bundleDiff?.removedBundles) ? bundleDiff.removedBundles : []
  const changedBundles = Array.isArray(bundleDiff?.changedBundles) ? bundleDiff.changedBundles : []
  const addedApiRoutes = Array.isArray(bundleDiff?.addedApiRoutes) ? bundleDiff.addedApiRoutes : []
  const removedApiRoutes = Array.isArray(bundleDiff?.removedApiRoutes) ? bundleDiff.removedApiRoutes : []
  const addedRoutes = Array.isArray(bundleDiff?.addedRoutes) ? bundleDiff.addedRoutes : []
  const addedKeywords = Array.isArray(bundleDiff?.addedKeywords) ? bundleDiff.addedKeywords : []
  const addedFlags = Array.isArray(bundleDiff?.addedFlags) ? bundleDiff.addedFlags : []
  const semanticEvidence = Array.isArray(semanticChange?.highValueEvidence) ? semanticChange.highValueEvidence : []
  const semanticReasons = Array.isArray(semanticChange?.reasons) ? semanticChange.reasons : []
  const freshSurface = Array.isArray(routeApi?.freshDiscoveries) ? routeApi.freshDiscoveries : []
  const dormantToLive = Array.isArray(routeApi?.dormantToLive) ? routeApi.dormantToLive : []
  const liveToDormant = Array.isArray(routeApi?.liveToDormant) ? routeApi.liveToDormant : []
  const liveApi = Array.isArray(routeApi?.liveApiRoutes) ? routeApi.liveApiRoutes : []
  const recentTimelineEvents = Array.isArray(activationTimeline?.recent?.events) ? activationTimeline.recent.events : []
  const newTimelineEvents = Array.isArray(activationTimeline?.newEvents) ? activationTimeline.newEvents : []
  const hasBundleEvidence = bundleDiff?.comparable === true || Number(intelligence?.bundleCount || 0) > 0

  return <div className="rounded-3xl border border-white/10 bg-[#05070a] p-4 sm:p-5 xl:col-span-12">
    <SectionTitle title="Feature Activation Intelligence" subtitle="Production feature-state, semantic change, route/API monitoring, activation timeline, evidence quality, and explainable decisions" right={<span className={`rounded-full border px-3 py-1 text-xs font-medium ${style.badge}`}>{classification}</span>} />
    <div className="grid gap-4 lg:grid-cols-[1.1fr_0.9fr]">
      <div className="rounded-2xl border border-white/10 bg-black/25 p-4"><div className="text-[11px] uppercase tracking-[0.22em] text-slate-500">Current State <IndicatorHelp label="Current State" /></div><div className="mt-3 flex items-center gap-3"><span className={`h-3 w-3 rounded-full ${style.dot}`} /><div className={`text-xl font-semibold ${style.text}`}>{classification}</div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-white/10 bg-black/20 p-3"><div className="text-[10px] uppercase tracking-[0.2em] text-slate-500">Build / Bundle Fingerprint <IndicatorHelp label="Build / Bundle Fingerprint" /></div><div className="mt-2 break-all font-mono text-sm text-slate-200">{evidence?.currentBuildId || "UNKNOWN"}</div><div className="mt-1 text-xs text-slate-500">{evidence?.buildChanged ? "Fingerprint changed" : "Fingerprint stable"}{intelligence?.buildIdSource ? ` · ${String(intelligence.buildIdSource).replaceAll("_", " ")}` : ""}</div></div><div className="rounded-xl border border-white/10 bg-black/20 p-3"><div className="text-[10px] uppercase tracking-[0.2em] text-slate-500">Previous Build <IndicatorHelp label="Previous Build" /></div><div className="mt-2 break-all font-mono text-sm text-slate-200">{evidence?.previousBuildId || "UNKNOWN"}</div><div className="mt-1 text-xs text-slate-500">Comparable {evidence?.comparable ? "YES" : "NO"} · {Number(intelligence?.bundleCount || 0)} bundles</div></div></div></div>
      <div className="grid grid-cols-2 gap-3"><div className="rounded-2xl border border-white/10 bg-black/25 p-4"><div className="text-[11px] uppercase tracking-[0.2em] text-slate-500">Unlocks <IndicatorHelp label="Unlocks" /></div><div className="mt-2 text-3xl font-semibold text-white">{unlockedFlags.length}</div></div><div className="rounded-2xl border border-white/10 bg-black/25 p-4"><div className="text-[11px] uppercase tracking-[0.2em] text-slate-500">Activated Routes <IndicatorHelp label="Activated Routes" /></div><div className="mt-2 text-3xl font-semibold text-white">{activatedRoutes.length}</div></div><div className="rounded-2xl border border-white/10 bg-black/25 p-4"><div className="text-[11px] uppercase tracking-[0.2em] text-slate-500">Convergence <IndicatorHelp label="Convergence" /></div><div className={`mt-2 text-xl font-semibold ${evidence?.convergence ? "text-amber-300" : "text-slate-300"}`}>{evidence?.convergence ? "YES" : "NO"}</div></div><div className="rounded-2xl border border-white/10 bg-black/25 p-4"><div className="text-[11px] uppercase tracking-[0.2em] text-slate-500">Activation Cluster <IndicatorHelp label="Activation Cluster" /></div><div className={`mt-2 text-xl font-semibold ${evidence?.activationCluster ? "text-red-300" : "text-slate-300"}`}>{evidence?.activationCluster ? "YES" : "NO"}</div></div></div>
    </div>

    {activationDecision && <div className="mt-4 rounded-2xl border border-violet-500/20 bg-violet-500/[0.03] p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="text-[11px] font-semibold uppercase tracking-[0.24em] text-violet-300">Activation Decision Engine v1 <IndicatorHelp label="Activation Decision Engine v1" /></div><div className="mt-1 text-xs text-slate-500">Gated decision layer combining semantic significance, cross-domain correlation, evidence quality, and observed activation transitions.</div></div><span className={`w-fit rounded-full border px-3 py-1 text-[10px] font-semibold ${decisionTone(activationDecision.state)}`}>{String(activationDecision.state || "QUIET").replaceAll("_", " ")}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><div className="rounded-xl border border-white/10 bg-black/20 p-3"><div className="text-[10px] uppercase tracking-[0.18em] text-slate-500">Decision Strength <IndicatorHelp label="Decision Strength" /></div><div className="mt-2 text-2xl font-semibold text-violet-300">{Number(activationDecision?.decisionStrength || 0)}/100</div></div><div className="rounded-xl border border-white/10 bg-black/20 p-3"><div className="text-[10px] uppercase tracking-[0.18em] text-slate-500">Semantic <IndicatorHelp label="Semantic" /></div><div className="mt-2 text-2xl font-semibold text-fuchsia-300">{Number(activationDecision?.scores?.semanticChange || 0)}</div></div><div className="rounded-xl border border-white/10 bg-black/20 p-3"><div className="text-[10px] uppercase tracking-[0.18em] text-slate-500">Correlation <IndicatorHelp label="Correlation" /></div><div className="mt-2 text-2xl font-semibold text-cyan-300">{Number(activationDecision?.scores?.correlation || 0)}</div></div><div className="rounded-xl border border-white/10 bg-black/20 p-3"><div className="text-[10px] uppercase tracking-[0.18em] text-slate-500">Confidence <IndicatorHelp label="Confidence" /></div><div className="mt-2 text-2xl font-semibold text-emerald-300">{Number(activationDecision?.scores?.evidenceConfidence || 0)}</div></div><div className="rounded-xl border border-white/10 bg-black/20 p-3"><div className="text-[10px] uppercase tracking-[0.18em] text-slate-500">Timeline <IndicatorHelp label="Timeline" /></div><div className="mt-2 text-2xl font-semibold text-orange-300">{Number(activationDecision?.scores?.activationTimeline || 0)}</div></div></div>{decisionReasons.length > 0 && <div className="mt-4 space-y-1 text-[11px] leading-5 text-slate-400">{decisionReasons.slice(0,4).map((reason:string,index:number)=><div key={index}>• {reason}</div>)}</div>}<div className="mt-3 text-[11px] text-slate-500">{activationDecision.interpretation} {activationDecision.caution}</div></div>}

    {activationTimeline && <div className="mt-4 rounded-2xl border border-orange-500/20 bg-orange-500/[0.03] p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="text-[11px] font-semibold uppercase tracking-[0.24em] text-orange-300">Activation Timeline v2.1 <IndicatorHelp label="Activation Timeline v2.1" /></div><div className="mt-1 text-xs text-slate-500">Persistent multi-domain sequence with a separate confidence score for evidence quality.</div></div><span className={`w-fit rounded-full border px-3 py-1 text-[10px] font-semibold ${timelineTone(activationTimeline.classification)}`}>{String(activationTimeline.classification || "QUIET").replaceAll("_", " ")} · {Number(activationTimeline.score || 0)}/100</span></div>
      <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><div className="rounded-xl border border-white/10 bg-black/20 p-3"><div className="text-[10px] uppercase tracking-[0.18em] text-slate-500">Evidence Confidence <IndicatorHelp label="Evidence Confidence" /></div><div className={`mt-2 text-2xl font-semibold ${confidenceTone(evidenceConfidence?.level)}`}>{Number(evidenceConfidence?.score || 0)}/100</div><div className="mt-1 text-[10px] text-slate-500">{String(evidenceConfidence?.level || "NO_EVIDENCE").replaceAll("_", " ")}</div></div><div className="rounded-xl border border-white/10 bg-black/20 p-3"><div className="text-[10px] uppercase tracking-[0.18em] text-slate-500">High Confidence <IndicatorHelp label="High Confidence" /></div><div className="mt-2 text-2xl font-semibold text-emerald-300">{Number(evidenceConfidence?.highConfidenceCount || 0)}</div></div><div className="rounded-xl border border-white/10 bg-black/20 p-3"><div className="text-[10px] uppercase tracking-[0.18em] text-slate-500">Flags Tracked <IndicatorHelp label="Flags Tracked" /></div><div className="mt-2 text-2xl font-semibold text-white">{Number(activationTimeline?.flagHistory?.observed || 0)}</div></div><div className="rounded-xl border border-white/10 bg-black/20 p-3"><div className="text-[10px] uppercase tracking-[0.18em] text-slate-500">Flag Transitions <IndicatorHelp label="Flag Transitions" /></div><div className="mt-2 text-2xl font-semibold text-fuchsia-300">{Number(activationTimeline?.flagHistory?.transitionsThisSweep || 0)}</div></div><div className="rounded-xl border border-white/10 bg-black/20 p-3"><div className="text-[10px] uppercase tracking-[0.18em] text-slate-500">Recent Domains <IndicatorHelp label="Recent Domains" /></div><div className="mt-2 text-2xl font-semibold text-cyan-300">{Number(activationTimeline?.recent?.domainCount || 0)}</div></div><div className="rounded-xl border border-white/10 bg-black/20 p-3"><div className="text-[10px] uppercase tracking-[0.18em] text-slate-500">New Events <IndicatorHelp label="New Events" /></div><div className="mt-2 text-2xl font-semibold text-orange-300">{newTimelineEvents.length}</div></div></div>
      {strongestEvidence.length > 0 && <div className="mt-4"><div className="mb-2 text-[10px] uppercase tracking-[0.2em] text-slate-500">Strongest evidence <IndicatorHelp label="Strongest evidence" /></div><div className="flex flex-wrap gap-2">{strongestEvidence.slice(0,8).map((item:any,index:number)=><span key={`${item.type}-${index}`} className="rounded-full border border-white/10 bg-black/30 px-2 py-1 text-[10px] text-slate-300">{shortEventType(item.type)} · <b className={confidenceTone(item.confidence >= 90 ? "VERY_HIGH" : item.confidence >= 80 ? "HIGH" : item.confidence >= 65 ? "MEDIUM" : "LOW")}>{item.confidence}%</b></span>)}</div></div>}
      {recentTimelineEvents.length > 0 && <div className="mt-4"><div className="mb-2 text-[10px] uppercase tracking-[0.2em] text-slate-500">Rolling 60-minute sequence</div><div className="space-y-2">{recentTimelineEvents.slice().reverse().slice(0,12).map((event:any,index:number)=><div key={`${event.id || event.type}-${index}`} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-white/10 bg-black/20 px-4 py-3"><div className="min-w-0"><div className="text-xs font-semibold text-slate-200">{shortEventType(event.type)}</div><div className="mt-1 break-all font-mono text-[10px] text-slate-500">{event.subject || event.detail || event.domain}</div></div><div className="flex flex-wrap items-center gap-2 text-[10px]"><span className="rounded-full border border-cyan-500/20 bg-cyan-500/10 px-2 py-1 text-cyan-300">{event.domain}</span><span className="font-mono text-slate-500">{event.seenAt ? new Date(event.seenAt).toLocaleString() : "—"}</span></div></div>)}</div></div>}
      <div className="mt-3 text-[11px] leading-5 text-slate-500">{evidenceConfidence?.methodology || activationTimeline.caution}</div></div>}

    {routeApi && <div className="mt-4 rounded-2xl border border-emerald-500/20 bg-emerald-500/[0.03] p-4"><div className="flex items-start justify-between gap-3"><div><div className="text-[11px] font-semibold uppercase tracking-[0.24em] text-emerald-300">Route + API Discovery v2 <IndicatorHelp label="Route + API Discovery v2" /></div><div className="mt-1 text-xs text-slate-500">Tracks learned same-origin surfaces and dormant → live transitions.</div></div><span className={`rounded-full border px-3 py-1 text-[10px] font-semibold ${dormantToLive.length ? "border-red-500/30 bg-red-500/10 text-red-300" : "border-emerald-500/30 bg-emerald-500/10 text-emerald-300"}`}>{dormantToLive.length ? `${dormantToLive.length} ACTIVATED` : "NO NEW ACTIVATION"}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><div className="rounded-xl border border-white/10 bg-black/20 p-3"><div className="text-[10px] text-slate-500">DISCOVERED <IndicatorHelp label="DISCOVERED" /></div><div className="mt-2 text-2xl font-semibold">{Number(routeApi?.discovered?.total || 0)}</div></div><div className="rounded-xl border border-white/10 bg-black/20 p-3"><div className="text-[10px] text-slate-500">FRESH <IndicatorHelp label="FRESH" /></div><div className="mt-2 text-2xl font-semibold text-cyan-300">{freshSurface.length}</div></div><div className="rounded-xl border border-white/10 bg-black/20 p-3"><div className="text-[10px] text-slate-500">LIVE APIS <IndicatorHelp label="LIVE APIS" /></div><div className="mt-2 text-2xl font-semibold text-orange-300">{liveApi.length}</div></div><div className="rounded-xl border border-white/10 bg-black/20 p-3"><div className="text-[10px] text-slate-500">DORMANT → LIVE <IndicatorHelp label="DORMANT \u2192 LIVE" /></div><div className="mt-2 text-2xl font-semibold text-red-300">{dormantToLive.length}</div></div><div className="rounded-xl border border-white/10 bg-black/20 p-3"><div className="text-[10px] text-slate-500">LIVE → DORMANT <IndicatorHelp label="LIVE \u2192 DORMANT" /></div><div className="mt-2 text-2xl font-semibold text-slate-300">{liveToDormant.length}</div></div></div></div>}

    {semanticChange && <div className="mt-4 rounded-2xl border border-fuchsia-500/20 bg-fuchsia-500/[0.03] p-4"><div className="flex justify-between gap-3"><div><div className="text-[11px] font-semibold uppercase tracking-[0.24em] text-fuchsia-300">Semantic Change Score <IndicatorHelp label="Semantic Change Score" /></div><div className="mt-1 text-xs text-slate-500">Separates routine bundle churn from activation-relevant meaning.</div></div><span className={`h-fit rounded-full border px-3 py-1 text-[10px] font-semibold ${semanticTone(semanticChange.level)}`}>{semanticChange.level || "BASELINE"} · {Number(semanticChange.score || 0)}/100</span></div>{semanticEvidence.length > 0 && <div className="mt-4 flex flex-wrap gap-2">{semanticEvidence.slice(0,16).map((item:string)=><span key={item} className="rounded-full border border-fuchsia-500/20 bg-fuchsia-500/10 px-2 py-1 text-[10px] text-fuchsia-300">{item}</span>)}</div>}{semanticReasons.length > 0 && <div className="mt-3 text-[11px] text-slate-400">{semanticReasons.slice(0,4).join(" ")}</div>}</div>}

    {hasBundleEvidence && <div className="mt-4 rounded-2xl border border-cyan-500/20 bg-cyan-500/[0.03] p-4"><div className="text-[11px] font-semibold uppercase tracking-[0.24em] text-cyan-300">Bundle Diff Intelligence <IndicatorHelp label="Bundle Diff Intelligence" /></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-xl border border-white/10 bg-black/20 p-3">Added <b className="float-right text-cyan-300">{addedBundles.length}</b></div><div className="rounded-xl border border-white/10 bg-black/20 p-3">Changed <b className="float-right text-yellow-300">{changedBundles.length}</b></div><div className="rounded-xl border border-white/10 bg-black/20 p-3">Removed <b className="float-right text-slate-300">{removedBundles.length}</b></div><div className="rounded-xl border border-white/10 bg-black/20 p-3">New APIs <b className="float-right text-orange-300">{addedApiRoutes.length}</b></div></div>{changedBundles.length > 0 && <div className="mt-3 text-[10px] text-slate-500">Latest changed bundle: {shortHash(changedBundles[0]?.currentSha256)}</div>}{(addedRoutes.length + addedKeywords.length + addedFlags.length + removedApiRoutes.length) > 0 && <div className="mt-3 text-[10px] text-slate-500">Semantic references changed: {addedRoutes.length + addedKeywords.length + addedFlags.length + removedApiRoutes.length}</div>}</div>}

    {!!dormantRoutes.length && <div className="mt-4"><div className="mb-2 text-[11px] uppercase tracking-[0.22em] text-slate-500">Dormant Routes <IndicatorHelp label="Dormant Routes" /></div><div className="space-y-2">{dormantRoutes.map((route,index)=><div key={`${route.route || "unknown"}-${index}`} className="flex justify-between rounded-xl border border-white/10 bg-black/20 px-4 py-3"><div className="font-mono text-sm text-slate-200">{route.route || "Unknown route"}</div><div className="text-xs text-slate-500">HTTP {route.status ?? "—"}</div></div>)}</div></div>}
    <div className="mt-4 rounded-xl border border-white/10 bg-black/20 p-3 text-xs text-slate-500">Activation Decision and Evidence Confidence are explainable evidence states, not probabilities of launch. Temporal proximity, reachability, on-chain activity, or code references do not by themselves prove causality, claim readiness, reward eligibility, or launch readiness.</div>
  </div>
}
