export const indicatorGuideLinks: Record<string, string> = {
  "Score": "score",
  "Radar Score": "score",
  "Intensity": "score",
  "Flight Instruments": "score",
  "Total Files": "files",
  "Added": "files",
  "Changed": "files",
  "Movement": "files",
  "Changed %": "files",
  "Movement %": "files",
  "Snapshot": "snapshot",
  "Signal Tape": "snapshot",
  "Check-in Tape": "snapshot",
  "Trend Graph": "trend",
  "Historical Movement": "trend",
  "Trend": "trend",
  "Velocity": "trend",
  "Burst / 5m": "trend",
  "Signal Type": "tags",
  "Signals & Tags": "tags",
  "Pattern Highlights": "tags",
  "Priority Readout": "tags",
  "Executive Readout": "tags",
  "Legacy heuristic signal": "heuristics",
  "Activation heuristic": "heuristics",
  "Operational Intelligence": "heuristics",
  "Confidence": "heuristics",
  "Readiness State": "heuristics",
  "Terminal Status": "heuristics",
  "Pattern Boost": "heuristics",
  "Alpha Score": "heuristics",
  "Alpha Class": "heuristics",
  "Trigger State": "heuristics",
  "Suggested Action": "heuristics",
  "ETA": "heuristics",
  "Feature Activation Intelligence": "bundles",
  "Build / Bundle Fingerprint": "bundles",
  "Previous Build": "bundles",
  "Comparable": "bundles",
  "Bundle Diff Intelligence": "bundles",
  "Current State": "bundles",
  "Unlocks": "routes",
  "Activated Routes": "routes",
  "Convergence": "routes",
  "Activation Cluster": "routes",
  "Route + API Discovery v2": "routes",
  "DISCOVERED": "routes",
  "FRESH": "routes",
  "LIVE APIS": "routes",
  "DORMANT → LIVE": "routes",
  "LIVE → DORMANT": "routes",
  "Dormant Routes": "routes",
  "Semantic Change Score": "semantic",
  "Semantic": "semantic",
  "Activation Decision Engine v1": "decision",
  "Decision Strength": "decision",
  "Activation Timeline v2.1": "timeline",
  "Timeline": "timeline",
  "Flags Tracked": "timeline",
  "Flag Transitions": "timeline",
  "Recent Domains": "timeline",
  "New Events": "timeline",
  "Evidence Confidence": "confidence",
  "High Confidence": "confidence",
  "Strongest evidence": "confidence",
  "API Response Drift": "api",
  "Evidence Correlation": "correlation",
  "Temporal Correlation": "correlation",
  "Correlation": "correlation",
  "Evidence": "correlation",
  "Domains": "correlation",
  "API": "correlation",
  "Backend": "correlation",
  "Web Surface": "correlation",
  "On-chain": "correlation",
  "Window": "correlation",
  "Span": "correlation",
  "Sequence": "correlation",
  "On-chain Intelligence": "chain",
  "Fresh Trigger": "chain",
  "Last 5 Minutes": "chain",
  "Chain score": "chain",
  "wPOND Distribution Cycle Predictor": "pattern",
  "Pattern Match": "pattern",
  "Pattern Components": "pattern",
  "Cadence similarity": "pattern",
  "Delay similarity": "pattern",
  "proximity": "pattern",
  "Historical Baseline": "pattern",
  "Funding Cadence": "cadence",
  "Claim After Funding": "cadence",
  "Predictor": "cadence",
  "Statistical funding window": "cadence",
  "Claim window after funding": "cadence",
  "Operational Automation Confidence": "cadence",
  "Reward Distributor Intelligence": "distributor",
  "1h Flow": "distributor",
  "6h Flow": "distributor",
  "24h Flow": "distributor",
  "SURGING": "distributor",
  "BURSTING": "distributor",
  "ACTIVE": "distributor",
  "COOLING": "distributor",
  "QUIET": "distributor",
  "1h Velocity": "distributor-stats",
  "Bursts": "distributor-stats",
  "Median Transfer": "distributor-stats",
  "Anomalies": "distributor-stats",
  "largest": "distributor-stats",
  "Observed Reward Recipients": "recipients",
  "Recipient Mix": "recipients",
  "Wallet": "recipients",
  "Status": "recipients",
  "wPOND": "recipients",
  "Transfers": "recipients",
  "First Seen": "recipients",
  "Last Seen": "recipients",
  "Last Tx": "recipients",
  "Radar Heartbeat": "heartbeat",
  "Next expected sweep": "heartbeat",
  "Last success": "heartbeat",
  "Freshness": "heartbeat",
  "Source": "heartbeat",
  "Scheduler": "heartbeat",
  "Radar Reliability": "health",
  "Observability": "health",
  "Navigation": "health",
  "Document": "health",
  "First-party": "health",
  "First-party APIs": "health",
  "Radar Trust": "health",
  "trigger": "health",
  "capture": "health",
  "chain": "health",
  "radar": "health",
  "publish": "health",
  "Telegram": "telegram-health",
  "Bot": "telegram-health",
  "Chat": "telegram-health",
  "Last health check": "telegram-health",
  "Last Radar alert": "telegram-health",
  "Last chain alert": "telegram-health",
  "Sentinel Intelligence": "sentinel",
  "Trigger Reason": "sentinel",
  "Changed Surfaces": "sentinel",
  "Max Priority": "sentinel",
  "Threshold Flags": "sentinel",
  "Evidence & Telegram": "evidence",
  "Claims available": "evidence",
  "Would notify": "evidence",
  "Observation only": "evidence",
  "Not sent": "evidence",
  "FUNDS_MOVEMENT": "eligibility",
  "WEB_CHANGE": "eligibility",
  "MONITORING_PROBLEM": "eligibility",
  "Coverage": "eligibility",
  "Legacy Telegram Delivery History": "history",
  "Recent Alerts": "history",
  "ALERT": "history",
  "Decision Engine Calibration": "calibration",
  "Exact Evidence": "calibration",
  "Ground Truth Covered": "calibration",
  "Threshold Changes": "calibration",
  "Recommendation": "calibration",
  "SENSITIVE": "calibration",
  "DEFAULT": "calibration",
  "CONSERVATIVE": "calibration",
  "Signals": "metrics",
  "False Signals": "metrics",
  "Precision": "metrics",
  "Recall": "metrics",
  "False Signal Rate": "metrics",
  "Median Lead": "metrics",
  "Guía": "reading",
  "Metodología": "reading",
  "Q&A": "reading"
}
